name: 'Make a GitHub release'
description: ''
inputs:
  tag:
    description: ''
    required: true
  token:
    description: 'GitHub token'
    required: true
  artifacts:
    description: 'Comma separated list of artifact names'
    required: true
  artifacts-path:
    description: 'Path to the folder that contains the artifacts'
    required: true
    default: '.'
runs:
  using: 'node12'
  main: 'dist/index.js'
