name: 'Make a GitHub release'
description: ''
inputs:
  tag:
    description: ''
    required: true
  token:
    description: 'GitHub token'
    required: true
  artifact:
    description: 'Path to the artifact that will be uploaded as a release asset.'
    required: true
  release-asset-name:
    description: 'The name of the asset that will be uploaded to the release.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
