name: 'Check if a release exists'
description: 'Check if a release exists. The action fails if the tag exists.'
inputs:
  tag:
    description: 'Path to the package.json file'
    required: true
  token:
    description: 'GitHub token'
    required: true
outputs:
  exists:
    description: 'Indicates whether the release version exists or not.'
runs:
  using: 'node12'
  main: 'dist/index.js'
