name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./angular
        run: npm ci

      - name: Run unit tests
        working-directory: ./angular
        run: npm run test:ci

      - name: Code coverage
        uses: codecov/codecov-action@v2.1.0

      - name: Build app
        working-directory: ./angular
        run: npm run build:ci
