name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./angular
        run: npm ci

      - name: Build app
        working-directory: ./angular
        run: npm run build:ci

  test-angular:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./angular
        run: npm ci

      - name: Run unit tests
        working-directory: ./angular
        run: npm run test:ci

      - name: Code coverage
        uses: codecov/codecov-action@v2.1.0

  build-electron:
    needs: build-angular
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./electron-app
        run: npm ci

      - name: Typescript
        working-directory: ./electron-app
        run: npm run tsc:prod

      - name: Make
        working-directory: ./electron-app
        run: npm run make

      - name: Read app version
        id: read-version
        uses: ./.github/actions/read-version

      - name: Upload a Build Artifact
        working-directory: ./electron-app/out
        uses: actions/upload-artifact@v2.2.4
        with:
          name: release-${{ matrix.os }}-${{ steps.read-version.outputs.version }}
          path: ./make

  check-if-release-exists:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Read app version
        id: read-version
        uses: ./.github/actions/read-version

      - name: Check if release exists
        id: check-if-release-exists
        uses: ./.github/actions/check-if-release-exists
        with:
          tag: v${{ steps.read-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  gh-release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [build-electron, check-if-release-exists]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Read app version
        id: read-version
        uses: ./.github/actions/read-version

      - name: Download build artifacts
        id: download-artifacts
        uses: actions/download-artifact@v2.0.10
        with:
          path: ./artifacts

      # - name: Download build artifact for windows
      #   id: download-windows-artifact
      #   env:
      #     zip-name: release-windows-latest-${{ steps.read-version.outputs.version }}.zip
      #   uses: actions/download-artifact@v2.0.10
      #   with:
      #     name: ${{ env.zip-name }}
      #     path: ${{ env.zip-name }}

      # - name: Download build artifact for linux
      #   id: download-linux-artifact
      #   env:
      #     zip-name: release-ubuntu-latest-${{ steps.read-version.outputs.version }}.zip
      #   uses: actions/download-artifact@v2.0.10
      #   with:
      #     name: ${{ env.zip-name }}
      #     path: ${{ env.zip-name }}

      # - name: Download build artifact for mac
      #   id: download-mac-artifact
      #   env:
      #     zip-name: release-macos-latest-${{ steps.read-version.outputs.version }}.zip
      #   uses: actions/download-artifact@v2.0.10
      #   with:
      #     name: ${{ env.zip-name }}
      #     path: ${{ env.zip-name }}

      # - name: Release to GitHub
      #   uses: ncipollo/release-action@v1.8.9
      #   env:
      #     version: ${{ steps.read-version.outputs.version }}
      #   with:
      #     artifacts: release-windows-latest-${{ env.version }}.zip, release-ubuntu-latest-${{ env.version }}.zip, release-macos-latest-${{ env.version }}.zip
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: v${{ env.version }}

      - name: ls
        run: ls -la

      - name: Create zips
        id: create-zips
        env:
          windows-zip-name: release-windows-latest-${{ steps.read-version.outputs.version }}.zip
          linux-zip-name: release-ubuntu-latest-${{ steps.read-version.outputs.version }}.zip
          mac-zip-name: release-macos-latest-${{ steps.read-version.outputs.version }}.zip
        run: |
          tar -cz -f ./${{ env.windows-zip-name }} -C ./artifacts/${{ env.windows-zip-name }} .
          tar -cz -f ./${{ env.linux-zip-name }} -C ./artifacts/${{ env.linux-zip-name }} .
          tar -cz -f ./${{ env.mac-zip-name }} -C ./artifacts/${{ env.mac-zip-name }} .
          echo "::set-output name=windows-zip-name::${{ env.windows-zip-name }}"
          echo "::set-output name=linux-zip-name::${{ env.linux-zip-name }}"
          echo "::set-output name=mac-zip-name::${{ env.mac-zip-name }}"

      - name: Release to GitHub
        uses: ./.github/actions/github-release
        env:
          version: ${{ steps.read-version.outputs.version }}
        with:
          artifacts: ${{ steps.create-zips.outputs.windows-zip-name }}, ${{ steps.create-zips.outputs.linux-zip-name }}, ${{ steps.create-zips.outputs.mac-zip-name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.version }}
          artifacts-path: ${{ github.workspace }}
