name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./angular
        run: npm ci

      - name: Build app
        working-directory: ./angular
        run: npm run build:ci

  test-angular:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./angular
        run: npm ci

      - name: Run unit tests
        working-directory: ./angular
        run: npm run test:ci

      - name: Code coverage
        uses: codecov/codecov-action@v2.1.0

  build-electron:
    needs: build-angular
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./electron-app
        run: npm ci

      - name: Typescript
        working-directory: ./electron-app
        run: npm run tsc:prod

      - name: Make
        working-directory: ./electron-app
        run: npm run make

      - name: Read app version
        id: read-version
        uses: ./.github/actions/read-version

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: release-${{ matrix.os }}-${{ steps.read-version.outputs.version }}
          path: ./electron-app/out/make

  check-if-release-exists:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Read app version
        id: read-version
        uses: ./.github/actions/read-version

      - name: Check if release exists
        id: check-if-release-exists
        uses: ./.github/actions/check-if-release-exists
        with:
          tag: v${{ steps.read-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  gh-release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [build-electron, check-if-release-exists]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Read app version
        id: read-version
        uses: ./.github/actions/read-version

      - name: Download build artifacts
        id: download-artifacts
        uses: actions/download-artifact@v2.0.10
        with:
          path: ./artifacts

      - name: Release to GitHub
        uses: ./.github/actions/github-release
        env:
          version: ${{ steps.read-version.outputs.version }}
          windows-artifact: release-windows-latest-${{ steps.read-version.outputs.version }}/squirrel.windows/x64/finance-manager-electron-0.1.0 Setup.exe
          linux-deb-artifact: release-ubuntu-latest-${{ steps.read-version.outputs.version }}/deb/x64/finance-manager-electron_0.1.0_amd64.deb
          linux-rpm-artifact: release-ubuntu-latest-${{ steps.read-version.outputs.version }}/rpm/x64/finance-manager-electron-0.1.0-1.x86_64.rpm
          mac-artifact: release-macos-latest-${{ steps.read-version.outputs.version }}/zip/darwin/x64/finance-manager-electron-darwin-x64-0.1.0.zip
        with:
          artifacts: ${{ env.windows-artifact }}, ${{ env.linux-deb-artifact }}, ${{ env.linux-rpm-artifact }}, ${{ env.mac-artifact }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.version }}
