name: Angular app CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
		defaults:
			run:
				working-directory: ./angular

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Build app
        run: npm build
