name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./angular
        run: npm ci

      - name: Run unit tests
        working-directory: ./angular
        run: npm run test:ci

      - name: Code coverage
        uses: codecov/codecov-action@v2.1.0

      - name: Build app
        working-directory: ./angular
        run: npm run build:ci

  build-electron:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./electron-app
        run: npm ci

      - name: Typescript
        working-directory: ./electron-app
        run: npm run tsc:prod

      - name: Make
        working-directory: ./electron-app
        run: npm run make

  # build-electron-win:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2.4.0
  #       with:
  #         node-version: 12

  #     - name: Install global dependencies
  #       run: npm ci

  #     - name: Install dependencies
  #       working-directory: ./electron-app
  #       run: npm ci

  #     - name: Typescript
  #       working-directory: ./electron-app
  #       run: npm run tsc:prod

  #     - name: Make
  #       working-directory: ./electron-app
  #       run: npm run make:win32

  # build-electron-linux:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2.4.0
  #       with:
  #         node-version: 12

  #     - name: Install global dependencies
  #       run: npm ci

  #     - name: Install dependencies
  #       working-directory: ./electron-app
  #       run: npm ci

  #     - name: Typescript
  #       working-directory: ./electron-app
  #       run: npm run tsc:prod

  #     - name: Make
  #       working-directory: ./electron-app
  #       run: npm run make:linux

  # build-electron-macos:
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2.4.0
  #       with:
  #         node-version: 12

  #     - name: Install global dependencies
  #       run: npm ci

  #     - name: Install dependencies
  #       working-directory: ./electron-app
  #       run: npm ci

  #     - name: Typescript
  #       working-directory: ./electron-app
  #       run: npm run tsc:prod

  #     - name: Make
  #       working-directory: ./electron-app
  #       run: npm run make:mas

  # build-electron-darwin:
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2.4.0
  #       with:
  #         node-version: 12

  #     - name: Install global dependencies
  #       run: npm ci

  #     - name: Install dependencies
  #       working-directory: ./electron-app
  #       run: npm ci

  #     - name: Typescript
  #       working-directory: ./electron-app
  #       run: npm run tsc:prod

  #     - name: Make
  #       working-directory: ./electron-app
  #       run: npm run make:darwin
