name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./angular
        run: npm ci

      - name: Build app
        working-directory: ./angular
        run: npm run build:ci

  test-angular:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./angular
        run: npm ci

      - name: Run unit tests
        working-directory: ./angular
        run: npm run test:ci

      - name: Code coverage
        uses: codecov/codecov-action@v2.1.0

  build-electron:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Install global dependencies
        run: npm ci

      - name: Install dependencies
        working-directory: ./electron-app
        run: npm ci

      - name: Typescript
        working-directory: ./electron-app
        run: npm run tsc:prod

      - name: Make
        working-directory: ./electron-app
        run: npm run make

      - name: Read app version
        id: read-version
        uses: ./.github/actions/read-version
        env:
          VERSION: ${{ steps.read-version.outputs.version }}
          ZIP_NAME: release-${{ env.VERSION }}.tar.gz

      - name: Create tar
        run: tar -cz -f ./${{ env.ZIP_NAME }} ./out/*

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.ZIP_NAME }}

  # gh-release:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2.4.0
  #       with:
  #         node-version: 12

  #     - name: Read app version
  #       id: read-version
  #       uses: ./.github/actions/read-version
  #       env:
  #         VERSION: ${{ steps.read-version.outputs.version }}
  #         ZIP_NAME: release-${{ env.VERSION }}.tar.gz

  #     - name: Download a Build Artifact
  #       uses: actions/download-artifact@v2.0.10
  #       with:
  #         name: ${{ env.ZIP_NAME }}

  #     - name: Release to GitHub
  #     - uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: ${{ env.ZIP_NAME }}
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         tag: v${{ env.version }}
