name: Debug release check

on:
  workflow_dispatch:

jobs:
  check-if-release-exists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Read app version
        id: read-version
        uses: ./.github/actions/read-version

      - name: Check if release exists
        uses: ./.github/actions/check-if-release-exists
        with:
          tag: v${{ steps.read-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
