name: Debug release check

on:
  workflow_dispatch:

jobs:
  check-if-release-exists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Read app version
        id: read-version
        uses: ./.github/actions/read-version

      - name: Check if release exists
        id: release-check
        uses: ./.github/actions/check-if-release-exists
        with:
          tag: v${{ steps.read-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo
        run: echo ${{ steps.release-check.outputs.exists }}

      - name: Set job output
        run:

  other-job:
    needs: check-if-release-exists
    # if: ${{ needs.check-if-release-exists.outputs.exists != true }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 12

      - name: Echo
        run: echo ${{ needs.check-if-release-exists.outputs.exists }}
